name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: CRGPT
          OPENAI_API_KEY: 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
          # Optional
          LANGUAGE: Chinese
          MODEL:
          top_p: 1
          temperature: 1